src/Entity/PcmCyclists.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PcmCyclistsRepository")
 */
class PcmCyclists
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $IDCyclist;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstname;

    /**
     * @ORM\Column(type="integer")
     */
    private $fkIDteam;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $fkIDregion;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $birthdate;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $popularity;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $size;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $weight;

    /**
     * @ORM\Column(type="integer")
     */
    private $charac_i_plain;

    /**
     * @ORM\Column(type="integer")
     */
    private $charac_i_mountain;

    /**
     * @ORM\Column(type="integer")
     */
    private $charac_i_downhilling;

    /**
     * @ORM\Column(type="integer")
     */
    private $charac_i_cobble;

    /**
     * @ORM\Column(type="integer")
     */
    private $charac_i_timetrial;

    /**
     * @ORM\Column(type="integer")
     */
    private $charc_i_prologue;

    /**
     * @ORM\Column(type="integer")
     */
    private $charac_i_sprint;

    /**
     * @ORM\Column(type="integer")
     */
    private $charac_i_acceleration;

    /**
     * @ORM\Column(type="integer")
     */
    private $charac_i_endurance;

    /**
     * @ORM\Column(type="integer")
     */
    private $charac_i_resistance;

    /**
     * @ORM\Column(type="integer")
     */
    private $charac_i_recuperation;

    /**
     * @ORM\Column(type="integer")
     */
    private $charac_i_hill;

    /**
     * @ORM\Column(type="integer")
     */
    private $charac_i_baroudeur;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIDCyclist(): ?int
    {
        return $this->IDCyclist;
    }

    public function setIDCyclist(int $IDCyclist): self
    {
        $this->IDCyclist = $IDCyclist;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getFkIDteam(): ?int
    {
        return $this->fkIDteam;
    }

    public function setFkIDteam(int $fkIDteam): self
    {
        $this->fkIDteam = $fkIDteam;

        return $this;
    }

    public function getFkIDregion(): ?int
    {
        return $this->fkIDregion;
    }

    public function setFkIDregion(?int $fkIDregion): self
    {
        $this->fkIDregion = $fkIDregion;

        return $this;
    }

    public function getBirthdate(): ?string
    {
        return $this->birthdate;
    }

    public function setBirthdate(?string $birthdate): self
    {
        $this->birthdate = $birthdate;

        return $this;
    }

    public function getPopularity(): ?int
    {
        return $this->popularity;
    }

    public function setPopularity(?int $popularity): self
    {
        $this->popularity = $popularity;

        return $this;
    }

    public function getSize(): ?int
    {
        return $this->size;
    }

    public function setSize(?int $size): self
    {
        $this->size = $size;

        return $this;
    }

    public function getWeight(): ?string
    {
        return $this->weight;
    }

    public function setWeight(?string $weight): self
    {
        $this->weight = $weight;

        return $this;
    }

    public function getCharacIPlain(): ?int
    {
        return $this->charac_i_plain;
    }

    public function setCharacIPlain(int $charac_i_plain): self
    {
        $this->charac_i_plain = $charac_i_plain;

        return $this;
    }

    public function getCharacIMountain(): ?int
    {
        return $this->charac_i_mountain;
    }

    public function setCharacIMountain(int $charac_i_mountain): self
    {
        $this->charac_i_mountain = $charac_i_mountain;

        return $this;
    }

    public function getCharacIDownhilling(): ?int
    {
        return $this->charac_i_downhilling;
    }

    public function setCharacIDownhilling(int $charac_i_downhilling): self
    {
        $this->charac_i_downhilling = $charac_i_downhilling;

        return $this;
    }

    public function getCharacICobble(): ?int
    {
        return $this->charac_i_cobble;
    }

    public function setCharacICobble(int $charac_i_cobble): self
    {
        $this->charac_i_cobble = $charac_i_cobble;

        return $this;
    }

    public function getCharacITimetrial(): ?int
    {
        return $this->charac_i_timetrial;
    }

    public function setCharacITimetrial(int $charac_i_timetrial): self
    {
        $this->charac_i_timetrial = $charac_i_timetrial;

        return $this;
    }

    public function getCharcIPrologue(): ?int
    {
        return $this->charc_i_prologue;
    }

    public function setCharcIPrologue(int $charc_i_prologue): self
    {
        $this->charc_i_prologue = $charc_i_prologue;

        return $this;
    }

    public function getCharacISprint(): ?int
    {
        return $this->charac_i_sprint;
    }

    public function setCharacISprint(int $charac_i_sprint): self
    {
        $this->charac_i_sprint = $charac_i_sprint;

        return $this;
    }

    public function getCharacIAcceleration(): ?int
    {
        return $this->charac_i_acceleration;
    }

    public function setCharacIAcceleration(int $charac_i_acceleration): self
    {
        $this->charac_i_acceleration = $charac_i_acceleration;

        return $this;
    }

    public function getCharacIEndurance(): ?int
    {
        return $this->charac_i_endurance;
    }

    public function setCharacIEndurance(int $charac_i_endurance): self
    {
        $this->charac_i_endurance = $charac_i_endurance;

        return $this;
    }

    public function getCharacIResistance(): ?int
    {
        return $this->charac_i_resistance;
    }

    public function setCharacIResistance(int $charac_i_resistance): self
    {
        $this->charac_i_resistance = $charac_i_resistance;

        return $this;
    }

    public function getCharacIRecuperation(): ?int
    {
        return $this->charac_i_recuperation;
    }

    public function setCharacIRecuperation(int $charac_i_recuperation): self
    {
        $this->charac_i_recuperation = $charac_i_recuperation;

        return $this;
    }

    public function getCharacIHill(): ?int
    {
        return $this->charac_i_hill;
    }

    public function setCharacIHill(int $charac_i_hill): self
    {
        $this->charac_i_hill = $charac_i_hill;

        return $this;
    }

    public function getCharacIBaroudeur(): ?int
    {
        return $this->charac_i_baroudeur;
    }

    public function setCharacIBaroudeur(int $charac_i_baroudeur): self
    {
        $this->charac_i_baroudeur = $charac_i_baroudeur;

        return $this;
    }
}

src/Controller/PCMController.php
<?php

namespace App\Controller;

use App\Entity\PCMCountry;
use App\Entity\PcmCyclists;
use App\Entity\PCMRegions;
use App\Entity\PcmTeams;
use App\Repository\PCMCountryRepository;
use App\Repository\PcmCyclistsRepository;
use App\Repository\PCMRegionsRepository;
use App\Repository\PcmTeamsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\DomCrawler\Crawler;

class PCMController extends AbstractController
{


    public function __construct(PcmCyclistsRepository $repository, PcmTeamsRepository $teamRepo, PCMCountryRepository $countryRepo , PCMRegionsRepository $regionRepo)
    {
        $this->repo = $repository;
        $this->teamRepo = $teamRepo;
        $this->regionRepo = $regionRepo;
        $this->countryRepo = $countryRepo;

    }

    /**
     * @Route("/cyclist/{idPCM}/", name="cyclist.idPCM")
     * @param EntityManagerInterface $em
     * @param Request $request
     * @param $ranks
     * @return Response
     */
    public function displayCyclist(EntityManagerInterface $em,int $idPCM,Request $request): Response
    {
        $cyclist = $this->repo->findOneBy([
            'IDCyclist' => $idPCM
        ]);

        $team = $this->teamRepo->findOneBy([
            'IDTeam' => $cyclist->getFkIDteam()
        ]
        );

        $nation = $this->regionRepo->findOneBy([
            'IdRegion' => $cyclist->getFkIDregion()
            ]
        );

        return $this->render('pcm/fiche.html.twig', [
            'controller_name' => 'PCMController',
            'cyclist' => $cyclist,
            'team' => $team,
            'nation' => $nation
        ]);
    }

    /**
     * @Route("/teams", name="listTeam")
     * @param EntityManagerInterface $em
     * @param Request $request
     * @param $ranks
     * @return Response
     */
    public function displayListTeam(EntityManagerInterface $em,Request $request): Response
    {

        $teams = $this->teamRepo->findAll();

        return $this->render('pcm/listTeam.html.twig', [
            'controller_name' => 'PCMController',
            'teams' => $teams
        ]);
    }

    /**
     * @Route("/teams/search", name="teams.search")
     * @param EntityManagerInterface $em
     * @param Request $request
     * @return Response
     */
    public function searchTeam(Request $request): Response
    {

        $teams = $this->teamRepo->findAll();

        $q = $request->query->get('q'); // use "term" instead of "q" for jquery-ui
        $results = $this->getDoctrine()->getRepository('App:PcmTeams')->findBy([
            'name' => $q
        ]);

        dump($results);

        return $this->render('pcm/listTeam.html.twig', [
            'results' => $results,
            'teams' => $teams
        ]);
    }


    /**
     * @Route("/cyclists/{idPCMTeam}/", name="cyclists.idPCMTeam")
     * @param EntityManagerInterface $em
     * @param Request $request
     * @param $ranks
     * @return Response
     */
    public function displayTeam(EntityManagerInterface $em,int $idPCMTeam,Request $request): Response
    {
        $cyclists = $this->repo->findBy([
            'fkIDteam' => $idPCMTeam
        ]);

        $team = $this->teamRepo->findOneBy([
                'IDTeam' => $idPCMTeam
            ]
        );

        return $this->render('pcm/ficheTeam.html.twig', [
            'controller_name' => 'PCMController',
            'cyclists' => $cyclists,
            'team' => $team
        ]);
    }

    /**
     * @return float
     */
    /*public function calculAVG($cyclist): float
    {
        //5 highest note without : descente - baroudeur - acceleration
        $n = array(
            //$cyclist->getCharcIPrologue(),
            $cyclist->getCharacISprint(),
            $cyclist->getCharacIPlain(),
            $cyclist->getCharacITimetrial(),
            $cyclist->getCharacIResistance(),
            $cyclist->getCharacIRecuperation(),
            $cyclist->getCharacIMountain(),
            $cyclist->getCharacIHill(),
            $cyclist->getCharacICobble(),
            $cyclist->getCharacIEndurance()
        );
        rsort($n);

        $top5 = array_slice($n, 0, 5);

        dump($top5);
        $avg =round(array_sum($top5)/count($top5));
        dump($avg);

        return $avg;

    }*/







    /**
     * @Route("/importDataPCM", name="import_data_pcm",methods={"GET"})
     * @param EntityManagerInterface $em
     * @param PcmCyclistsRepository $repo
     */
    public function importCyclist(EntityManagerInterface $em, PcmCyclistsRepository $repo)
    {
        // ENTRER LE NUM DE FICHIER
        //$idFile=1; //952 cyclist
        //$idFile=2; //808 cyclist
        //$idFile=3; //929 cyclist
        //$idFile=4; //965 cyclist
        //$idFile=5; //758 cyclist
        //$idFile=6; //753 cyclist + 1 after without fkIDteam and IrRegion
        //$idFile=0; //

        for($i=1;$i<7;$i++){
            $this->extractDataForCyclist($em, $repo, $i);
        }

        return $this->render('home/index.html.twig', [
            'controller_name' => 'HomeController'
        ]);

    }

    /**
     * @Route("/importTeamPCM", name="import_team_pcm",methods={"GET"})
     * @param EntityManagerInterface $em
     * @param PcmTeamsRepository $repo
     */
    public function importTeamPCM(EntityManagerInterface $em, PcmTeamsRepository $repo)
    {

        $crawler = new Crawler();
        $crawler->addXmlContent(file_get_contents('DYN_team.xml'));
        $results = $crawler->filter("NewDataSet");

        $crawler = $crawler->filter("NewDataSet > DYN_team");

        $teams = $crawler->each(
            function (Crawler $node, $i) {
                $rowTeam = $node->children()->each(
                    function (Crawler $node2,$i){
                        $name = $node2->first()->nodeName();
                        $value = $node2->first()->text();
                        return array($name => $value);
                    });
                return $rowTeam;
            }
        );

        foreach ($teams as $team){
            $theTeam = array();
            foreach ($team as $ligne) {
                foreach ($ligne as $key => $value) {
                    $theTeam[$key] = $value;
                }
            }

            $elem = $repo->findOneBy([
                'IDTeam' => $theTeam["IDteam"]
            ]);

            if($elem == null){
                $pcmTeam = new PcmTeams();

                if(!array_key_exists("gene_sz_name",$theTeam) ){
                    $theTeam["gene_sz_name"] = -100;
                }
                $pcmTeam->setIDTeam($theTeam["IDteam"]);
                $pcmTeam->setName($theTeam["gene_sz_name"]);

                $em->persist($pcmTeam);
                $em->flush();
            }
        }
        return $this->render('home/index.html.twig', [
            'controller_name' => 'HomeController'
        ]);

    }

    /**
     * @param EntityManagerInterface $em
     * @param PcmCyclistsRepository $repo
     * @param int $idFile
     */
    public function extractDataForCyclist(EntityManagerInterface $em, PcmCyclistsRepository $repo, int $idFile): void
    {
        $crawler = new Crawler();
        $crawler->addXmlContent(file_get_contents('DYN_cyclist' . $idFile . '.xml'));
        $results = $crawler->filter("NewDataSet");

        $crawler = $crawler->filter("NewDataSet > DYN_cyclist");

        $cyclists = $crawler->each(
            function (Crawler $node, $i) {
                $rowCyclist = $node->children()->each(
                    function (Crawler $node2, $i) {
                        $name = $node2->first()->nodeName();
                        $value = $node2->first()->text();
                        return array($name => $value);
                    });
                return $rowCyclist;
            }
        );


        foreach ($cyclists as $cyclist) {
            $theCyclist = array();
            foreach ($cyclist as $ligne) {
                foreach ($ligne as $key => $value) {
                    $theCyclist[$key] = $value;
                }
            }
            $elem = $repo->findOneBy([
                'IDCyclist' => $theCyclist["IDcyclist"]
            ]);

            if ($elem == null) {
                $pcmCyclist = new PcmCyclists();
                if (!array_key_exists("fkIDregion", $theCyclist)) {
                    $theCyclist["fkIDregion"] = -100;
                }
                if (!array_key_exists("fkIDteam", $theCyclist)) {
                    $theCyclist["fkIDteam"] = -100;
                }
                $pcmCyclist->setIDCyclist($theCyclist["IDcyclist"]);
                $pcmCyclist->setBirthdate($theCyclist["gene_i_birthdate"]);
                $pcmCyclist->setCharacIAcceleration($theCyclist["charac_i_acceleration"]);
                $pcmCyclist->setCharacIBaroudeur($theCyclist["charac_i_baroudeur"]);
                $pcmCyclist->setCharacICobble($theCyclist["charac_i_cobble"]);
                $pcmCyclist->setCharacIDownhilling($theCyclist["charac_i_downhilling"]);
                $pcmCyclist->setCharacIEndurance($theCyclist["charac_i_endurance"]);
                $pcmCyclist->setCharacIHill($theCyclist["charac_i_hill"]);
                $pcmCyclist->setCharacIMountain($theCyclist["charac_i_mountain"]);
                $pcmCyclist->setCharacIPlain($theCyclist["charac_i_plain"]);
                $pcmCyclist->setCharacIRecuperation($theCyclist["charac_i_recuperation"]);
                $pcmCyclist->setCharacIResistance($theCyclist["charac_i_resistance"]);
                $pcmCyclist->setCharacITimetrial($theCyclist["charac_i_timetrial"]);
                $pcmCyclist->setCharacISprint($theCyclist["charac_i_sprint"]);
                $pcmCyclist->setCharcIPrologue($theCyclist["charac_i_prologue"]);

templates/pcm/fiche.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{ cyclist.firstName }} {{ cyclist.lastName }}{% endblock %}

{% block body %}
    <div class="container mt-4">

        <h1 class="mt-5">{{ cyclist.firstName }} {{ cyclist.lastName }}</h1>

        <div>
            <span class="font-weight-bold">Team</span> : {{ team.name }}
        </div>
        <div>
            <span class="font-weight-bold">Nationalité</span> : {{ nation.name }}
        </div>

        {% include 'pcm/panelStats.html.twig' with {'cyclist':  cyclist} %}

    </div>
{% endblock %}

templates/pcm/ficheTeam.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{ team.name }}{% endblock %}

{% block body %}
    <div class="container mt-4">

        <h1 class="mt-5">{{ team.name }}</h1>

        <div>
            <span class="font-weight-bold">Team</span> : {{ team.name }}
        </div>

        <ul class="list-group list-team">
            {% for cyclist in cyclists %}
                <li class="list-group-item">
                    <a href="" class="infoPlayer">
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-info-circle-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412l-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533L8.93 6.588zM8 5.5a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"/>
                        </svg>
                        <div class="infoPlayerContent col-md-10">{% include 'pcm/panelStats.html.twig' with {'cyclist':  cyclist} %}</div>

                    </a>
                    <a href="{{path('cyclist.idPCM',{idPCM: cyclist.IDCyclist})}}">{{ cyclist.firstName }} {{ cyclist.lastName }}</a>
                    <!--<div class="note_gene">
                        { avg }
                    </div>-->
                </li>

            {% endfor %}
        </ul>
    </div>
{% endblock %}

templates/pcm/listTeam.html.twig
{% extends 'base.html.twig' %}

{% block title %} Liste des équipes{% endblock %}

{% block body %}
    <div class="container mt-4">



        <h1 class="mt-5">Liste des Equipes</h1>

        <div class="col-md-4">
            <ul class="list-group list-team">
                {% for team in teams | sort %}
                    <li class="list-group-item"><a href="{{path('cyclists.idPCMTeam',{idPCMTeam: team.IDTeam})}}">{{ team.name }}</a></li>
                {% endfor %}
            </ul>
        </div>


    </div>
{% endblock %}

templates/pcm/panelStats.html.twig
<div class="panel-stat-pcm col-md-4 col-sm-12">
    <div class="row">
        <div class="col">
            <div class="row">
                <div class="col-md-4">
                    <div class="row">
                        <div class="col-md-6">PLA</div>
                        <div class="col-md-6 {% if cyclist.characIPlain > 79 %}more80{% endif %} {% if cyclist.characIPlain > 69 and cyclist.characIPlain < 80 %}more70{% endif %}
">{{ cyclist.characIPlain }}</div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="row">
                        <div class="col-md-6">PAV</div>
                        <div class="col-md-6 {% if cyclist.characICobble > 79 %}more80{% endif %} {% if cyclist.characICobble > 69 and cyclist.characICobble < 80 %}more70{% endif %}
">{{ cyclist.characICobble }}</div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="row">
                        <div class="col-md-6">BAR</div>
                        <div class="col-md-6 {% if cyclist.characIBaroudeur > 79 %}more80{% endif %} {% if cyclist.characIBaroudeur > 69 and cyclist.characIBaroudeur < 80 %}more70{% endif %}
">{{ cyclist.characIBaroudeur }}</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="row">
                <div class="col-md-4">
                    <div class="row">
                        <div class="col-md-6">MON</div>
                        <div class="col-md-6 {% if cyclist.characIMountain> 79 %}more80{% endif %} {% if cyclist.characIMountain > 69 and cyclist.characIMountain < 80 %}more70{% endif %}
">{{ cyclist.characIMountain }}</div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="row">
                        <div class="col-md-6">SPR</div>
                        <div class="col-md-6 {% if cyclist.characISprint> 79 %}more80{% endif %} {% if cyclist.characISprint > 69 and cyclist.characISprint < 80 %}more70{% endif %}
">{{ cyclist.characISprint }}</div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="row">
                        <div class="col-md-6">END</div>
                        <div class="col-md-6 {% if cyclist.characIEndurance> 79 %}more80{% endif %} {% if cyclist.characIEndurance > 69 and cyclist.characIEndurance < 80 %}more70{% endif %}
">{{ cyclist.characIEndurance }}</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="row">
                <div class="col-md-4">
                    <div class="row">
                        <div class="col-md-6">VAL</div>
                        <div class="col-md-6 {% if cyclist.characIHill > 79 %}more80{% endif %} {% if cyclist.characIHill > 69 and cyclist.characIHill < 80 %}more70{% endif %}
">{{ cyclist.characIHill }}</div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="row">
                        <div class="col-md-6">ACC</div>
                        <div class="col-md-6 {% if cyclist.characIAcceleration > 79 %}more80{% endif %} {% if cyclist.characIAcceleration > 69 and cyclist.characIAcceleration < 80 %}more70{% endif %}
">{{ cyclist.characIAcceleration }}</div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="row">
                        <div class="col-md-6">RES</div>
                        <div class="col-md-6 {% if cyclist.characIResistance > 79 %}more80{% endif %} {% if cyclist.characIResistance > 69 and cyclist.characIResistance < 80 %}more70{% endif %}
">{{ cyclist.characIResistance }}</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="row">
                <div class="col-md-4">
                    <div class="row">
                        <div class="col-md-6">CLM</div>
                        <div class="col-md-6 {% if cyclist.characITimetrial > 79 %}more80{% endif %} {% if cyclist.characITimetrial > 69 and cyclist.characITimetrial < 80 %}more70{% endif %}
">{{ cyclist.characITimetrial }}</div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="row">
                        <div class="col-md-6">DES</div>
                        <div class="col-md-6 {% if cyclist.characIDownhilling > 79 %}more80{% endif %} {% if cyclist.characIDownhilling > 69 and cyclist.characIDownhilling < 80 %}more70{% endif %}
">{{ cyclist.characIDownhilling }}</div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="row">
                        <div class="col-md-6">REC</div>
                        <div class="col-md-6 {% if cyclist.characIRecuperation > 79 %}more80{% endif %} {% if cyclist.characIRecuperation > 69 and cyclist.characIRecuperation < 80 %}more70{% endif %}
">{{ cyclist.characIRecuperation }}</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/pcm/search.json.twig
[{% for author in authors -%}
    {{ {id: author.id, text: author.__toString}|json_encode|raw }}
    {# use the following for jquery-ui
    {{ {value: author.id, label: author.__toString}|json_encode|raw }}
    #}
    {%- if not loop.last %},{% endif -%}
    {%- endfor %}]